server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tempcheck
    username: root
    password: 970413106565
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: tempcheck.spring@gmail.com
    password: dsmyfmphukywrsia
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
